title: μEDH
tagline: f:edh r<r
description: μEDH is a rarity-based deckbuilding constraint for EDH designed to promote budget brews and Johnny metas.
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
