title: μEDH
tagline: a rarity constrained EDH subset
description: μEDH is a rarity constrained EDH subset designed for budget brewers in Timmy metas.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
